name: Deploy App
on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build_app:
    needs: [test_app, lint_app]
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, window-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
