name: Deploy App
on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build_app:
    runs-on: ubuntu-latest
    needs: [test_app, lint_app]
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
