name: Deploy App
on: push
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        # run: echo
        uses: actions/checkout@v3
        # with:
        #   ref: ''
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint_app:
    runs-on: ubuntu-latest
    needs: test_app
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build_app:
    runs-on: ubuntu-latest
    needs: lint_app
    steps:
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...


