name: Print Pull Request Context
on:
  workflow_dispatch:
  pull_request:
    [opened, edit, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"