name: Test App
on: push
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository code
        # run: echo
        uses: actions/checkout@v3
        # with:
        #   ref: ''
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
